/**
 * 16×16 pixel-art sprites — single source of truth for UI and tray icons.
 * '.' = transparent. Other keys map to per-pet palette colors.
 */

import type { PetChoice } from "./pets";
import type { AnimationKey } from "./spriteState";

export const SPRITE_SIZE = 16;

export interface PetSpriteSet {
  palette: Record<string, string | null>;
  frames: Partial<Record<AnimationKey, readonly string[]>>;
}

/** Row-major sprite grids (each row exactly 16 characters). */
export const PET_SPRITES: Record<PetChoice, PetSpriteSet> = {
  cat: {
    palette: {
      ".": null,
      o: "#2a2118",
      O: "#e8a87c",
      W: "#fff8ee",
      E: "#2a2118",
      P: "#f0a8b8",
      A: "#d4885c",
    },
    frames: {
      idle: [
        "......oooo......",
        ".....oOOOOo.....",
        "....oOOOOOOo....",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo...",
        "....oOOOOo....",
        ".....oAAo.....",
        "......oo......",
        "..............",
        "..............",
        "..............",
        "..............",
      ],
      nudge: [
        "......oooo......",
        "....ooOOOOoo....",
        "....oOOOOOOo....",
        "...oOOEEEEOo...",
        "...oOOEEEEOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo...",
        "....oOOOOo....",
        ".....oAAo.....",
        "......oo......",
        "..............",
        "..............",
        "..............",
        "..............",
      ],
      happy: [
        "......oooo......",
        ".....oOOOOo.....",
        "....oOOOOOOo....",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPPPPOo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo...",
        "....oOOOOo....",
        ".....oAAo.....",
        "......oo......",
        "..............",
        "..............",
        "..............",
        "..............",
      ],
      sleeping: [
        "......oooo......",
        ".....oOOOOo.....",
        "....oOOOOOOo....",
        "...oOOO--OOo...",
        "...oOOO--OOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo...",
        "....oOOOOo....",
        ".....oAAo.....",
        "......oo......",
        "..............",
        "..............",
        "..............",
        "..............",
      ],
    },
  },
  dog: {
    palette: {
      ".": null,
      o: "#2a2118",
      O: "#c9a66b",
      W: "#fff8ee",
      E: "#2a2118",
      P: "#8b5a2b",
      A: "#a67c52",
    },
    frames: {
      idle: [
        "..............oo",
        ".......ooooooOOo",
        "......oOOOOOOOo.",
        ".....oOOOWWOOo..",
        ".....oOOOWWOOo..",
        "....oOOOOOOOOo..",
        "....oOOPOOOPOo..",
        "...oOOOOOOOOo...",
        "...oOOOOOOOo....",
        "..oOOOOOOo......",
        "..oOAAAAo.......",
        "...ooooo........",
        "................",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "....oo........oo",
        "....oOOOOooOOOo.",
        "....oOOOOOOOOo..",
        "....oOOEEEEOo...",
        "....oOOEEEEOo...",
        "...oOOOOOOOOo...",
        "...oOOPOOOPOo...",
        "..oOOOOOOOOo....",
        "..oOOOOOOOo.....",
        ".oOOOOOOo.......",
        ".oOAAAAo........",
        "..ooooo.........",
        "................",
        "................",
        "................",
        "................",
      ],
      happy: [
        "..............oo",
        ".......ooooooOOo",
        "......oOOOOOOOo.",
        ".....oOOOWWOOo..",
        ".....oOOOWWOOo..",
        "....oOOOOOOOOo..",
        "....oOOPPPPOo...",
        "...oOOOOOOOOo...",
        "...oOOOOOOOo....",
        "..oOOOOOOo......",
        "..oOAAAAo.......",
        "...ooooo........",
        "................",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "..............oo",
        ".......ooooooOOo",
        "......oOOOOOOOo.",
        ".....oOOO--OOo..",
        ".....oOOO--OOo..",
        "....oOOOOOOOOo..",
        "....oOOPOOOPOo..",
        "...oOOOOOOOOo...",
        "...oOOOOOOOo....",
        "..oOOOOOOo......",
        "..oOAAAAo.......",
        "...ooooo........",
        "................",
        "................",
        "................",
        "................",
      ],
    },
  },
  frog: {
    palette: {
      ".": null,
      o: "#2a2118",
      O: "#7cb87a",
      W: "#fff8ee",
      E: "#2a2118",
      P: "#5a9a4a",
      G: "#9ed49a",
    },
    frames: {
      idle: [
        "................",
        "....oo....oo....",
        "....OO....OO....",
        "...oOOOOOOOOo...",
        "...oOOOWWOOo....",
        "...oOOOWWOOo....",
        "..oOOOOOOOOo....",
        "..oOOPOOOPOo....",
        "..oOOOOOOOOo....",
        "...oOOOOOOo.....",
        "....oOOOOo......",
        ".....oPPo.......",
        "......oo........",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "................",
        "....oo....oo....",
        "....OO....OO....",
        "...oOOOOOOOOo...",
        "...oOOEEEEOo....",
        "...oOOEEEEOo....",
        "..oOOOOOOOOo....",
        "..oOOPOOOPOo....",
        "..oOOOOOOOOo....",
        "...oOOOOOOo.....",
        "....oOOOOo......",
        ".....oPPo.......",
        "......oo........",
        "................",
        "................",
        "................",
      ],
      happy: [
        "................",
        "....oo....oo....",
        "....OO....OO....",
        "...oOOOOOOOOo...",
        "...oOOOWWOOo....",
        "...oOOOWWOOo....",
        "..oOOOOOOOOo....",
        "..oOOGGGGOo.....",
        "..oOOOOOOOOo....",
        "...oOOOOOOo.....",
        "....oOOOOo......",
        ".....oPPo.......",
        "......oo........",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "................",
        "....oo....oo....",
        "....OO....OO....",
        "...oOOOOOOOOo...",
        "...oOOO--OOo....",
        "...oOOO--OOo....",
        "..oOOOOOOOOo....",
        "..oOOPOOOPOo....",
        "..oOOOOOOOOo....",
        "...oOOOOOOo.....",
        "....oOOOOo......",
        ".....oPPo.......",
        "......oo........",
        "................",
        "................",
        "................",
      ],
    },
  },
  turtle: {
    palette: {
      ".": null,
      o: "#2a2118",
      S: "#6b9e8a",
      G: "#9ed4b0",
      W: "#fff8ee",
      H: "#5a7a68",
    },
    frames: {
      idle: [
        "................",
        ".....oooooo.....",
        "...ooSSSSSSoo...",
        "..oSSGGGGSSo..",
        ".oSSGGWWGGSSo.",
        ".oSSGGWWGGSSo.",
        "oSSGGGGGGGGSSo",
        "oSSGGGGGGGGSSo",
        ".oSSGGGGGGSSo.",
        "..oSSSSSSSSo..",
        "...ooHHHHoo...",
        "....oooooo....",
        "................",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "................",
        ".....oooooo.....",
        "...ooSSSSSSoo...",
        "..oSSGGGGSSo..",
        ".oSSGGEEGGSSo.",
        ".oSSGGEEGGSSo.",
        "oSSGGGGGGGGSSo",
        "oSSGGGGGGGGSSo",
        ".oSSGGGGGGSSo.",
        "..oSSSSSSSSo..",
        "...ooHHHHoo...",
        "....oooooo....",
        "................",
        "................",
        "................",
        "................",
      ],
      happy: [
        "................",
        ".....oooooo.....",
        "...ooSSSSSSoo...",
        "..oSSGGGGSSo..",
        ".oSSGGWWGGSSo.",
        ".oSSGGWWGGSSo.",
        "oSSGGGGGGGGSSo",
        "oSSGGGGGGGGSSo",
        ".oSSGGGGGGSSo.",
        "..oSSSSSSSSo..",
        "...ooHHHHoo...",
        "....oooooo....",
        "................",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "................",
        ".....oooooo.....",
        "...ooSSSSSSoo...",
        "..oSSGGGGSSo..",
        ".oSSGG--GGSSo.",
        ".oSSGG--GGSSo.",
        "oSSGGGGGGGGSSo",
        "oSSGGGGGGGGSSo",
        ".oSSGGGGGGSSo.",
        "..oSSSSSSSSo..",
        "...ooHHHHoo...",
        "....oooooo....",
        "................",
        "................",
        "................",
        "................",
      ],
    },
  },
  pig: {
    palette: {
      ".": null,
      o: "#2a2118",
      O: "#f0a8b8",
      W: "#fff8ee",
      E: "#2a2118",
      P: "#e87898",
      A: "#f5c4d0",
    },
    frames: {
      idle: [
        "................",
        ".....oooooo.....",
        "....oOOOOOOo....",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPPPPOo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "................",
        ".....oooooo.....",
        "....oOOOOOOo....",
        "...oOOEEEEOo...",
        "...oOOEEEEOo...",
        "..oOOOOOOOOo..",
        "..oOOPPPPOo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      happy: [
        "................",
        ".....oooooo.....",
        "....oOOOOOOo....",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPPPPPo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "................",
        ".....oooooo.....",
        "....oOOOOOOo....",
        "...oOOO--OOo...",
        "...oOOO--OOo...",
        "..oOOOOOOOOo..",
        "..oOOPPPPOo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
    },
  },
  duck: {
    palette: {
      ".": null,
      o: "#2a2118",
      Y: "#f5d76e",
      O: "#e8b830",
      W: "#fff8ee",
      E: "#2a2118",
      B: "#f09030",
    },
    frames: {
      idle: [
        "................",
        "......oooo......",
        ".....oYYYYo.....",
        "....oYYYYYYo....",
        "...oYYOWWYOo...",
        "...oYYOWWYOo...",
        "..oYYYYYYYYo..",
        "..oYYYBYYo....",
        "..oYYYYYYo....",
        "...oYYYYo.......",
        "....oYYo........",
        ".....oo.........",
        "................",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "................",
        "......oooo......",
        ".....oYYYYo.....",
        "....oYYYYYYo....",
        "...oYYEEEYOo...",
        "...oYYEEEYOo...",
        "..oYYYYYYYYo..",
        "..oYYYBYYo....",
        "..oYYYYYYo....",
        "...oYYYYo.......",
        "....oYYo........",
        ".....oo.........",
        "................",
        "................",
        "................",
        "................",
      ],
      happy: [
        "................",
        "......oooo......",
        ".....oYYYYo.....",
        "....oYYYYYYo....",
        "...oYYOWWYOo...",
        "...oYYOWWYOo...",
        "..oYYYYYYYYo..",
        "..oYYYBBYo....",
        "..oYYYYYYo....",
        "...oYYYYo.......",
        "....oYYo........",
        ".....oo.........",
        "................",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "................",
        "......oooo......",
        ".....oYYYYo.....",
        "....oYYYYYYo....",
        "...oYYO--YOo...",
        "...oYYO--YOo...",
        "..oYYYYYYYYo..",
        "..oYYYBYYo....",
        "..oYYYYYYo....",
        "...oYYYYo.......",
        "....oYYo........",
        ".....oo.........",
        "................",
        "................",
        "................",
        "................",
      ],
    },
  },
  wolf: {
    palette: {
      ".": null,
      o: "#2a2118",
      O: "#9aa8c4",
      W: "#fff8ee",
      E: "#2a2118",
      G: "#6a7894",
      A: "#7888a8",
    },
    frames: {
      idle: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oGGGGo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOEEEEOo...",
        "...oOOEEEEOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oGGGGo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      happy: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOOAAAOOo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oGGGGo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOO--OOo...",
        "...oOOO--OOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oGGGGo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
    },
  },
  bear: {
    palette: {
      ".": null,
      o: "#2a2118",
      O: "#b8956a",
      W: "#fff8ee",
      E: "#2a2118",
      P: "#8b6848",
      A: "#d4a87c",
    },
    frames: {
      idle: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      nudge: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOEEEEOo...",
        "...oOOEEEEOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      happy: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOOWWOOo...",
        "...oOOOWWOOo...",
        "..oOOOOOOOOo..",
        "..oOOPPPPOo...",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
      sleeping: [
        "......oo....oo..",
        ".....oOOo..oOOo.",
        "....oOOOOOOOOo..",
        "...oOOO--OOo...",
        "...oOOO--OOo...",
        "..oOOOOOOOOo..",
        "..oOOPOOOPOo..",
        "..oOOOOOOOOo..",
        "...oOOOOOOo....",
        "....oOOOOo.....",
        "....oAAAAo.....",
        ".....oooo......",
        "................",
        "................",
        "................",
        "................",
      ],
    },
  },
};

function normalizeRow(row: string): string {
  if (row.length >= SPRITE_SIZE) return row.slice(0, SPRITE_SIZE);
  return row.padEnd(SPRITE_SIZE, ".");
}

export function getSpriteFrame(
  pet: PetChoice,
  animation: AnimationKey
): { palette: Record<string, string | null>; rows: readonly string[] } {
  const set = PET_SPRITES[pet];
  const raw =
    set.frames[animation] ??
    set.frames.idle ??
    PET_SPRITES.cat.frames.idle!;
  const rows = raw.map(normalizeRow);
  return { palette: set.palette, rows };
}

/** Flat RGBA buffer for PNG export (tray icons). */
export function spriteToRgba(
  pet: PetChoice,
  animation: AnimationKey,
  scale = 1
): { width: number; height: number; data: Uint8Array } {
  const { palette, rows } = getSpriteFrame(pet, animation);
  const base = SPRITE_SIZE;
  const width = base * scale;
  const height = base * scale;
  const data = new Uint8Array(width * height * 4);

  for (let y = 0; y < base; y++) {
    for (let x = 0; x < base; x++) {
      const ch = rows[y]?.[x] ?? ".";
      const hex = palette[ch] ?? null;
      const r = hex ? parseInt(hex.slice(1, 3), 16) : 0;
      const g = hex ? parseInt(hex.slice(3, 5), 16) : 0;
      const b = hex ? parseInt(hex.slice(5, 7), 16) : 0;
      const a = hex ? 255 : 0;

      for (let sy = 0; sy < scale; sy++) {
        for (let sx = 0; sx < scale; sx++) {
          const px = x * scale + sx;
          const py = y * scale + sy;
          const i = (py * width + px) * 4;
          data[i] = r;
          data[i + 1] = g;
          data[i + 2] = b;
          data[i + 3] = a;
        }
      }
    }
  }

  return { width, height, data };
}
